version: "3.9"

services:
  backend:
    build: ./backend
    container-name: connect-backend
    ports: 
      - "8000:8000"
    env_file:
      - "./.env"

    depends_on:
      - db
    
    volumes:
      - ./backend:/app

    command: >
      uvicorn app.main:app
      --host 0.0.0.0
      --port 8000
      --reload

  db:
    image: postgres:15
    container-name: connect-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: connect_db
    ports:
      -"5433:5433"
    volumes:
      postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

